name: Backend CI

on: push

jobs:
  run:
    name: Run on Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v3

      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: python -m pip install -U pip hatch

      - name: Lint
        run: hatch run lint

      - name: Test
        run: hatch run cov
