name: Deploy

on:
  push:
    branch: main
    tags:
      - 'v*'

env:
  IMAGE_NAME: us-central1-docker.pkg.dev/toxic-news/toxic-news/toxic-news

jobs:
  build-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Set env release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build
        run: docker buildx build . -t ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

      - name: Push
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
